### ISSUE TITLE
Getting an error while trying to run kivy-designer - Please help me to solve this

### ISSUE THREAD

**Issue by applicationhackman** [kivy/kivy-designer#164]
ERROR  ] [WinPygame   ] unable to set icon
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/kivy/core/window/window_pygame.py", line 215, in set_icon
    self._set_icon_standard(filename)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/kivy/core/window/window_pygame.py", line 227, in _set_icon_standard
    im = pygame.image.load(filename)
pygame.error: File is not a Windows BMP file

Getting an error while trying to run kivy-designer - mac el capitan

**Comment by aron-bordin** [comment]
I see that your env is trying to use pygame `ERROR ] [WinPygame ] unable to set icon`. So, check this bug and this comment: https://github.com/kivy/kivy/issues/3908#issuecomment-170799453
Is your installation OK? https://kivy.org/docs/installation/installation-osx.html

**Comment by krusaderjake** [comment]
I would suggest uninstalling pygame and getting SDL2 going with your version of KIVY (not the designer) since pygame is deprecated in KIVY. I also tried installing kivy-designer on Mac (Yosemite in my case) and could not quite get it going, but I was also trying to use pygame in the KIVY module. I see a common theme of things not working with pygame.

https://kivy.org/docs/installation/installation.html?highlight=development

Link above is how to install the development version of kivy on OSX. Might be a good restarting point for you. You should include any issues you are having with home brew if you are using that (i.e., any packages that can't be found). But maybe also try an install without using home brew using the steps in the link above and see how things go with that route.
